# this file is autogenerated byt the taskipy update_sample data task
# to re-generate it, along with all the json files in this dir, run:
#     task update_sample_data
# (requires taskipy: pip install taskipy)
from yt_napari.sample_data._generic_loader import load_sample_data


def sample_deeplynestedzoom():
    return load_sample_data("DeeplyNestedZoom")


def sample_enzo_64():
    return load_sample_data("Enzo_64")


def sample_galaxyclustermerger():
    return load_sample_data("GalaxyClusterMerger")


def sample_gaussiancloud():
    return load_sample_data("GaussianCloud")


def sample_hiresisolatedgalaxy():
    return load_sample_data("HiresIsolatedGalaxy")


def sample_isolatedgalaxy():
    return load_sample_data("IsolatedGalaxy")


def sample_popiii_mini():
    return load_sample_data("PopIII_mini")


def sample_smartstars():
    return load_sample_data("SmartStars")


def sample_cm1_tornado_lofs():
    return load_sample_data("cm1_tornado_lofs")
